version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:9000"
    volumes:
      - /home/nurbek/ItransitionNurbek:/var/www/html
    environment:
      DATABASE_URL: "mysql://nurbek:1@database:3307/itransitionNurbek?serverVersion=8.0.36&charset=utf8mb4"

  database:
    image: mysql:8.0.36
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: "itransitionNurbek"
      MYSQL_ROOT_PASSWORD: "1"
