version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./:/app
    environment:
      DATABASE_URL: "mysql://nurbek:1@database:3306/itransitionNurbek?serverVersion=8.0.36&charset=utf8mb4"

  database:
    image: mysql:8.0.36
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "itransitionNurbek"
      MYSQL_ROOT_PASSWORD: "1"
      MYSQL_USER: nurbek
      MYSQL_PASSWORD: "1"
    